apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregator-microservice-config
data:
  spring.application.name: "AggregatorMicroservice"
  server.port: "8080"
  
  mqtt.broker.url: "tcp://mosquitto:1883"
  mqtt.topic.hum: "sensor/humidity"
  mqtt.topic.temp: "sensor/temperature"
  mqtt.client.id: "aggregator"